
import SwiftUI




struct ImageExtension_Previews: PreviewProvider {
    
    static var previews: some View {
        ZStack {
            Color.black
            VStack {
                Image.ar
                Image.polls
                Image.slowMoCheck
                Image.recordTool
            }.foregroundColor(.white)
        }
    }
}


public extension Image {
    static var verifiedIcon: Image { Image("verifiedIcon", bundle: .module) }
    static var enterLobby: Image { Image("enterLobby", bundle: .module) }
    static var encoreLogoECentered: Image { Image("encoreLogoECentered", bundle: .module) }
    static var discordLogo: Image { Image("discordIcon", bundle: .module) }
    static var encoreWordmark: Image { Image("encoreWordmark", bundle: .module) }
    
    static var clapIcon: Image { Image("clapIcon", bundle: .module) }
    static var polls: Image { Image("polls", bundle: .module) }
    static var ar: Image { Image("ar", bundle: .module) }
    static var recordTool: Image { Image("recordTool", bundle: .module) }
    static var startCircleDash: Image { Image("startCircleDash", bundle: .module) }
    static var stopCircleDash: Image { Image("stopCircleDash", bundle: .module) }


    //Anron icons
    
    static var activity2: Image { Image("activity2", bundle: .module) }
    static var activityRec: Image { Image("activityRec", bundle: .module) }
    static var airplay: Image { Image("airplay", bundle: .module) }
    static var alertCircle: Image { Image("alertCircle", bundle: .module) }
    static var alertOctagon: Image { Image("alertOctagon", bundle: .module) }
    static var alertTriangle: Image { Image("alertTriangle", bundle: .module) }
    static var alignBottom: Image { Image("alignBottom", bundle: .module) }
    static var alignBottomRec: Image { Image("alignBottomRec", bundle: .module) }
    static var alignCenter: Image { Image("alignCenter", bundle: .module) }
    static var alignCenter2: Image { Image("alignCenter2", bundle: .module) }
    static var alignCenter2Rec: Image { Image("alignCenter2Rec", bundle: .module) }
    static var alignCenterRec: Image { Image("alignCenterRec", bundle: .module) }
    static var alignJustify: Image { Image("alignJustify", bundle: .module) }
    static var alignJustify2: Image { Image("alignJustify2", bundle: .module) }
    static var alignJustify2Rec: Image { Image("alignJustify2Rec", bundle: .module) }
    static var alignJustifyRec: Image { Image("alignJustifyRec", bundle: .module) }
    static var alignLeft: Image { Image("alignLeft", bundle: .module) }
    static var alignLeft2: Image { Image("alignLeft2", bundle: .module) }
    static var alignLeft2Rec: Image { Image("alignLeft2Rec", bundle: .module) }
    static var alignLeftRec: Image { Image("alignLeftRec", bundle: .module) }
    static var alignMiddle: Image { Image("alignMiddle", bundle: .module) }
    static var alignMiddleRec: Image { Image("alignMiddleRec", bundle: .module) }
    static var alignRight: Image { Image("alignRight", bundle: .module) }
    static var alignRight2: Image { Image("alignRight2", bundle: .module) }
    static var alignRight2Rec: Image { Image("alignRight2Rec", bundle: .module) }
    static var alignRightRec: Image { Image("alignRightRec", bundle: .module) }
    static var alignTop: Image { Image("alignTop", bundle: .module) }
    static var alignTopRec: Image { Image("alignTopRec", bundle: .module) }
    static var anchor: Image { Image("anchor", bundle: .module) }
    static var anchorRec: Image { Image("anchorRec", bundle: .module) }
    static var apperture: Image { Image("apperture", bundle: .module) }
    static var archive: Image { Image("archive", bundle: .module) }
    static var around: Image { Image("around", bundle: .module) }
    static var arrowBottom: Image { Image("arrowBottom", bundle: .module) }
    static var arrowBottomCircle: Image { Image("arrowBottomCircle", bundle: .module) }
    static var arrowBottomLeft: Image { Image("arrowBottomLeft", bundle: .module) }
    static var arrowBottomLeftCircle: Image { Image("arrowBottomLeftCircle", bundle: .module) }
    static var arrowBottomLeftRec: Image { Image("arrowBottomLeftRec", bundle: .module) }
    static var arrowBottomRec: Image { Image("arrowBottomRec", bundle: .module) }
    static var arrowBottomRight: Image { Image("arrowBottomRight", bundle: .module) }
    static var arrowBottomRightCircle: Image { Image("arrowBottomRightCircle", bundle: .module) }
    static var arrowBottomRightRec: Image { Image("arrowBottomRightRec", bundle: .module) }
    static var arrowCornerCcwLb: Image { Image("arrowCornerCcwLb", bundle: .module) }
    static var arrowCornerCcwLbRec: Image { Image("arrowCornerCcwLbRec", bundle: .module) }
    static var arrowCornerCcwLt: Image { Image("arrowCornerCcwLt", bundle: .module) }
    static var arrowCornerCcwLtRec: Image { Image("arrowCornerCcwLtRec", bundle: .module) }
    static var arrowCornerCcwRb: Image { Image("arrowCornerCcwRb", bundle: .module) }
    static var arrowCornerCcwRbRec: Image { Image("arrowCornerCcwRbRec", bundle: .module) }
    static var arrowCornerCcwRt: Image { Image("arrowCornerCcwRt", bundle: .module) }
    static var arrowCornerCcwRtRec: Image { Image("arrowCornerCcwRtRec", bundle: .module) }
    static var arrowCornerCwLb: Image { Image("arrowCornerCwLb", bundle: .module) }
    static var arrowCornerCwLbRec: Image { Image("arrowCornerCwLbRec", bundle: .module) }
    static var arrowCornerCwLt: Image { Image("arrowCornerCwLt", bundle: .module) }
    static var arrowCornerCwLtRec: Image { Image("arrowCornerCwLtRec", bundle: .module) }
    static var arrowCornerCwRb: Image { Image("arrowCornerCwRb", bundle: .module) }
    static var arrowCornerCwRbRec: Image { Image("arrowCornerCwRbRec", bundle: .module) }
    static var arrowCornerCwRt: Image { Image("arrowCornerCwRt", bundle: .module) }
    static var arrowCornerCwRtRec: Image { Image("arrowCornerCwRtRec", bundle: .module) }
    static var arrowLeft: Image { Image("arrowLeft", bundle: .module) }
    static var arrowLeftCircle: Image { Image("arrowLeftCircle", bundle: .module) }
    static var arrowLeftCurvedCircle: Image { Image("arrowLeftCurvedCircle", bundle: .module) }
    static var arrowLeftRec: Image { Image("arrowLeftRec", bundle: .module) }
    static var arrowRight: Image { Image("arrowRight", bundle: .module) }
    static var arrowRightCircle: Image { Image("arrowRightCircle", bundle: .module) }
    static var arrowRightCurvedCircle: Image { Image("arrowRightCurvedCircle", bundle: .module) }
    static var arrowRightRec: Image { Image("arrowRightRec", bundle: .module) }
    static var arrowsExpand: Image { Image("arrowsExpand", bundle: .module) }
    static var arrowsExpand2: Image { Image("arrowsExpand2", bundle: .module) }
    static var arrowsExpand2Rec: Image { Image("arrowsExpand2Rec", bundle: .module) }
    static var arrowsExpandRec: Image { Image("arrowsExpandRec", bundle: .module) }
    static var arrowsMove: Image { Image("arrowsMove", bundle: .module) }
    static var arrowsMove2: Image { Image("arrowsMove2", bundle: .module) }
    static var arrowsMove2Rec: Image { Image("arrowsMove2Rec", bundle: .module) }
    static var arrowsMoveRec: Image { Image("arrowsMoveRec", bundle: .module) }
    static var arrowSwap: Image { Image("arrowSwap", bundle: .module) }
    static var arrowSwapRec: Image { Image("arrowSwapRec", bundle: .module) }
    static var arrowTop: Image { Image("arrowTop", bundle: .module) }
    static var arrowTopCircle: Image { Image("arrowTopCircle", bundle: .module) }
    static var arrowTopLeft: Image { Image("arrowTopLeft", bundle: .module) }
    static var arrowTopLeftCircle: Image { Image("arrowTopLeftCircle", bundle: .module) }
    static var arrowTopLeftRec: Image { Image("arrowTopLeftRec", bundle: .module) }
    static var arrowTopRec: Image { Image("arrowTopRec", bundle: .module) }
    static var arrowTopRight: Image { Image("arrowTopRight", bundle: .module) }
    static var arrowTopRightCircle: Image { Image("arrowTopRightCircle", bundle: .module) }
    static var arrowTopRightRec: Image { Image("arrowTopRightRec", bundle: .module) }
    static var at: Image { Image("at", bundle: .module) }
    static var atom: Image { Image("atom", bundle: .module) }
    static var atRec: Image { Image("atRec", bundle: .module) }
    static var award: Image { Image("award", bundle: .module) }
    static var babyCarriage: Image { Image("babyCarriage", bundle: .module) }
    static var barchart: Image { Image("barchart", bundle: .module) }
    static var battery: Image { Image("battery", bundle: .module) }
    static var battery1: Image { Image("battery1", bundle: .module) }
    static var battery2: Image { Image("battery2", bundle: .module) }
    static var battery3: Image { Image("battery3", bundle: .module) }
    static var batteryCharging: Image { Image("batteryCharging", bundle: .module) }
    static var batterySlash: Image { Image("batterySlash", bundle: .module) }
    static var bed2: Image { Image("bed2", bundle: .module) }
    static var bed3: Image { Image("bed3", bundle: .module) }
    static var bell: Image { Image("bell", bundle: .module) }
    static var bellCheck: Image { Image("bellCheck", bundle: .module) }
    static var bellMinus: Image { Image("bellMinus", bundle: .module) }
    static var bellPlus: Image { Image("bellPlus", bundle: .module) }
    static var bellSlash: Image { Image("bellSlash", bundle: .module) }
    static var bluetooth: Image { Image("bluetooth", bundle: .module) }
    static var bluetoothRec: Image { Image("bluetoothRec", bundle: .module) }
    static var book: Image { Image("book", bundle: .module) }
    static var bookLibrary: Image { Image("bookLibrary", bundle: .module) }
    static var bookmark: Image { Image("bookmark", bundle: .module) }
    static var bookmarkCheck: Image { Image("bookmarkCheck", bundle: .module) }
    static var bookmarkMinus: Image { Image("bookmarkMinus", bundle: .module) }
    static var bookmarkPlus: Image { Image("bookmarkPlus", bundle: .module) }
    static var bookmarks: Image { Image("bookmarks", bundle: .module) }
    static var bookmarkSlash: Image { Image("bookmarkSlash", bundle: .module) }
    static var bookOpen: Image { Image("bookOpen", bundle: .module) }
    static var bookPlus: Image { Image("bookPlus", bundle: .module) }
    static var bookQueue: Image { Image("bookQueue", bundle: .module) }
    static var borderBottom: Image { Image("borderBottom", bundle: .module) }
    static var borderClear: Image { Image("borderClear", bundle: .module) }
    static var borderCommon: Image { Image("borderCommon", bundle: .module) }
    static var borderHorizontal: Image { Image("borderHorizontal", bundle: .module) }
    static var borderInner: Image { Image("borderInner", bundle: .module) }
    static var borderLeft: Image { Image("borderLeft", bundle: .module) }
    static var borderOuter: Image { Image("borderOuter", bundle: .module) }
    static var borderRight: Image { Image("borderRight", bundle: .module) }
    static var borderTop: Image { Image("borderTop", bundle: .module) }
    static var borderVertical: Image { Image("borderVertical", bundle: .module) }
    static var box: Image { Image("box", bundle: .module) }
    static var box2: Image { Image("box2", bundle: .module) }
    static var brackets: Image { Image("brackets", bundle: .module) }
    static var bracketsRec: Image { Image("bracketsRec", bundle: .module) }
    static var briefcase: Image { Image("briefcase", bundle: .module) }
    static var briefcase2: Image { Image("briefcase2", bundle: .module) }
    static var broadcast: Image { Image("broadcast", bundle: .module) }
    static var broadcastRec: Image { Image("broadcastRec", bundle: .module) }
    static var brush: Image { Image("brush", bundle: .module) }
    static var bulb: Image { Image("bulb", bundle: .module) }
    static var bulbSlash: Image { Image("bulbSlash", bundle: .module) }
    static var calendar: Image { Image("calendar", bundle: .module) }
    static var calendarArrowRight: Image { Image("calendarArrowRight", bundle: .module) }
    static var calendarCross: Image { Image("calendarCross", bundle: .module) }
    static var calendarDates: Image { Image("calendarDates", bundle: .module) }
    static var calendarEvent: Image { Image("calendarEvent", bundle: .module) }
    static var calendarMinus: Image { Image("calendarMinus", bundle: .module) }
    static var calendarNote: Image { Image("calendarNote", bundle: .module) }
    static var calendarNumber: Image { Image("calendarNumber", bundle: .module) }
    static var calendarPerson: Image { Image("calendarPerson", bundle: .module) }
    static var calendarPlus: Image { Image("calendarPlus", bundle: .module) }
    static var callIncoming: Image { Image("callIncoming", bundle: .module) }
    static var camera: Image { Image("camera", bundle: .module) }
    static var cameraSlash: Image { Image("cameraSlash", bundle: .module) }
    static var captions: Image { Image("captions", bundle: .module) }
    static var captions2: Image { Image("captions2", bundle: .module) }
    static var cast: Image { Image("cast", bundle: .module) }
    static var cd: Image { Image("cd", bundle: .module) }
    static var chartBar: Image { Image("chartBar", bundle: .module) }
    static var chartColumn: Image { Image("chartColumn", bundle: .module) }
    static var chartLine: Image { Image("chartLine", bundle: .module) }
    static var chartPie: Image { Image("chartPie", bundle: .module) }
    static var check: Image { Image("check", bundle: .module) }
    static var checkboxCircle: Image { Image("checkboxCircle", bundle: .module) }
    static var checkboxRec: Image { Image("checkboxRec", bundle: .module) }
    static var checkCircle: Image { Image("checkCircle", bundle: .module) }
    static var checkCircle2: Image { Image("checkCircle2", bundle: .module) }
    static var checkRec: Image { Image("checkRec", bundle: .module) }
    static var chevronDown: Image { Image("chevronDown", bundle: .module) }
    static var chevronDownRecRec: Image { Image("chevronDownRecRec", bundle: .module) }
    static var chevronLeft: Image { Image("chevronLeft", bundle: .module) }
    static var chevronLeftRecRec: Image { Image("chevronLeftRecRec", bundle: .module) }
    static var chevronRight: Image { Image("chevronRight", bundle: .module) }
    static var chevronRightRecRec: Image { Image("chevronRightRecRec", bundle: .module) }
    static var chevronsDown: Image { Image("chevronsDown", bundle: .module) }
    static var chevronsDownRec: Image { Image("chevronsDownRec", bundle: .module) }
    static var chevronsLeft: Image { Image("chevronsLeft", bundle: .module) }
    static var chevronsLeftRec: Image { Image("chevronsLeftRec", bundle: .module) }
    static var chevronsRight: Image { Image("chevronsRight", bundle: .module) }
    static var chevronsRightRec: Image { Image("chevronsRightRec", bundle: .module) }
    static var chevronsUp: Image { Image("chevronsUp", bundle: .module) }
    static var chevronsUpRec: Image { Image("chevronsUpRec", bundle: .module) }
    static var chevronUp: Image { Image("chevronUp", bundle: .module) }
    static var chevronUpRecRec: Image { Image("chevronUpRecRec", bundle: .module) }
    static var clock: Image { Image("clock", bundle: .module) }
    static var clockCheck: Image { Image("clockCheck", bundle: .module) }
    static var clockCross: Image { Image("clockCross", bundle: .module) }
    static var clockMinus: Image { Image("clockMinus", bundle: .module) }
    static var clockPlus: Image { Image("clockPlus", bundle: .module) }
    static var clockSlash: Image { Image("clockSlash", bundle: .module) }
    static var clockZzz: Image { Image("clockZzz", bundle: .module) }
    static var code: Image { Image("code", bundle: .module) }
    static var codeRec: Image { Image("codeRec", bundle: .module) }
    static var colorFilter: Image { Image("colorFilter", bundle: .module) }
    static var columnSpacing: Image { Image("columnSpacing", bundle: .module) }
    static var columnSpacingRec: Image { Image("columnSpacingRec", bundle: .module) }
    static var comment: Image { Image("comment", bundle: .module) }
    static var comment2: Image { Image("comment2", bundle: .module) }
    static var comment2Alert: Image { Image("comment2Alert", bundle: .module) }
    static var comment2Cancel: Image { Image("comment2Cancel", bundle: .module) }
    static var comment2Check: Image { Image("comment2Check", bundle: .module) }
    static var comment2Dots: Image { Image("comment2Dots", bundle: .module) }
    static var comment2Info: Image { Image("comment2Info", bundle: .module) }
    static var comment2Minus: Image { Image("comment2Minus", bundle: .module) }
    static var comment2Plus: Image { Image("comment2Plus", bundle: .module) }
    static var comment2Question: Image { Image("comment2Question", bundle: .module) }
    static var comment2Slash: Image { Image("comment2Slash", bundle: .module) }
    static var comment2Text: Image { Image("comment2Text", bundle: .module) }
    static var commentAlert: Image { Image("commentAlert", bundle: .module) }
    static var commentCancel: Image { Image("commentCancel", bundle: .module) }
    static var commentCheck: Image { Image("commentCheck", bundle: .module) }
    static var commentDots: Image { Image("commentDots", bundle: .module) }
    static var commentMinus: Image { Image("commentMinus", bundle: .module) }
    static var commentPlus: Image { Image("commentPlus", bundle: .module) }
    static var comments: Image { Image("comments", bundle: .module) }
    static var comments2: Image { Image("comments2", bundle: .module) }
    static var commentSlash: Image { Image("commentSlash", bundle: .module) }
    static var commentText: Image { Image("commentText", bundle: .module) }
    static var compass: Image { Image("compass", bundle: .module) }
    static var componentPin: Image { Image("componentPin", bundle: .module) }
    static var copy: Image { Image("copy", bundle: .module) }
    static var copyright: Image { Image("copyright", bundle: .module) }
    static var creditCard: Image { Image("creditCard", bundle: .module) }
    static var cross: Image { Image("cross", bundle: .module) }
    static var crossCircle: Image { Image("crossCircle", bundle: .module) }
    static var crosshair: Image { Image("crosshair", bundle: .module) }
    static var crossOctagon: Image { Image("crossOctagon", bundle: .module) }
    static var crossRec: Image { Image("crossRec", bundle: .module) }
    static var cut: Image { Image("cut", bundle: .module) }
    static var dashboard: Image { Image("dashboard", bundle: .module) }
    static var dashboard2: Image { Image("dashboard2", bundle: .module) }
    static var devices: Image { Image("devices", bundle: .module) }
    static var direction: Image { Image("direction", bundle: .module) }
    static var direction2: Image { Image("direction2", bundle: .module) }
    static var diskette: Image { Image("diskette", bundle: .module) }
    static var dollar: Image { Image("dollar", bundle: .module) }
    static var dollarCircle: Image { Image("dollarCircle", bundle: .module) }
    static var droplet: Image { Image("droplet", bundle: .module) }
    static var dropletSlash: Image { Image("dropletSlash", bundle: .module) }
    static var dumbell: Image { Image("dumbell", bundle: .module) }
    static var edit: Image { Image("edit", bundle: .module) }
    static var edit2: Image { Image("edit2", bundle: .module) }
    static var edit3: Image { Image("edit3", bundle: .module) }
    static var editSlash: Image { Image("editSlash", bundle: .module) }
    static var elements: Image { Image("elements", bundle: .module) }
    static var elementsPlus: Image { Image("elementsPlus", bundle: .module) }
    static var email: Image { Image("email", bundle: .module) }
    static var emails: Image { Image("emails", bundle: .module) }
    static var emotionHappy: Image { Image("emotionHappy", bundle: .module) }
    static var emotionNeutral: Image { Image("emotionNeutral", bundle: .module) }
    static var emotionSad: Image { Image("emotionSad", bundle: .module) }
    static var emotionSmile: Image { Image("emotionSmile", bundle: .module) }
    static var emotionWow: Image { Image("emotionWow", bundle: .module) }
    static var equalizer: Image { Image("equalizer", bundle: .module) }
    static var export: Image { Image("export", bundle: .module) }
    static var export2: Image { Image("export2", bundle: .module) }
    static var export3: Image { Image("export3", bundle: .module) }
    static var export4Rec: Image { Image("export4Rec", bundle: .module) }
    static var externalLink2: Image { Image("externalLink2", bundle: .module) }
    static var externalLinkRec: Image { Image("externalLinkRec", bundle: .module) }
    static var eye: Image { Image("eye", bundle: .module) }
    static var eyeSlash: Image { Image("eyeSlash", bundle: .module) }
    static var fastForward: Image { Image("fastForward", bundle: .module) }
    static var fastRewind: Image { Image("fastRewind", bundle: .module) }
    static var fileDownload: Image { Image("fileDownload", bundle: .module) }
    static var fileText: Image { Image("fileText", bundle: .module) }
    static var filmBoard: Image { Image("filmBoard", bundle: .module) }
    static var filmReel: Image { Image("filmReel", bundle: .module) }
    static var filmTape: Image { Image("filmTape", bundle: .module) }
    static var filter: Image { Image("filter", bundle: .module) }
    static var filter2: Image { Image("filter2", bundle: .module) }
    static var filterRec: Image { Image("filterRec", bundle: .module) }
    static var fire: Image { Image("fire", bundle: .module) }
    static var fireFill: Image { Image("fireFill", bundle: .module) }
    static var firstLine1: Image { Image("firstLine1", bundle: .module) }
    static var firstLine1Rec: Image { Image("firstLine1Rec", bundle: .module) }
    static var firstLine2: Image { Image("firstLine2", bundle: .module) }
    static var firstLine2Rec: Image { Image("firstLine2Rec", bundle: .module) }
    static var firstLine3: Image { Image("firstLine3", bundle: .module) }
    static var firstLine3Rec: Image { Image("firstLine3Rec", bundle: .module) }
    static var flag: Image { Image("flag", bundle: .module) }
    static var flag2: Image { Image("flag2", bundle: .module) }
    static var flag3: Image { Image("flag3", bundle: .module) }
    static var flashcard: Image { Image("flashcard", bundle: .module) }
    static var folder: Image { Image("folder", bundle: .module) }
    static var folderOpen: Image { Image("folderOpen", bundle: .module) }
    static var forward: Image { Image("forward", bundle: .module) }
    static var forward10: Image { Image("forward10", bundle: .module) }
    static var forward10Rec: Image { Image("forward10Rec", bundle: .module) }
    static var forward15: Image { Image("forward15", bundle: .module) }
    static var forward15Rec: Image { Image("forward15Rec", bundle: .module) }
    static var forward5: Image { Image("forward5", bundle: .module) }
    static var forward5Rec: Image { Image("forward5Rec", bundle: .module) }
    static var forwardAll: Image { Image("forwardAll", bundle: .module) }
    static var forwardAllRec: Image { Image("forwardAllRec", bundle: .module) }
    static var forwardRec: Image { Image("forwardRec", bundle: .module) }
    static var functions: Image { Image("functions", bundle: .module) }
    static var functionsRec: Image { Image("functionsRec", bundle: .module) }
    static var games: Image { Image("games", bundle: .module) }
    static var gear: Image { Image("gear", bundle: .module) }
    static var gear2: Image { Image("gear2", bundle: .module) }
    static var gift: Image { Image("gift", bundle: .module) }
    static var glasses: Image { Image("glasses", bundle: .module) }
    static var glassesVr: Image { Image("glassesVr", bundle: .module) }
    static var globe: Image { Image("globe", bundle: .module) }
    static var globe2: Image { Image("globe2", bundle: .module) }
    static var globeFill: Image { Image("globeFill", bundle: .module) }
    static var gps: Image { Image("gps", bundle: .module) }
    static var gpsSlash: Image { Image("gpsSlash", bundle: .module) }
    static var hardDrive: Image { Image("hardDrive", bundle: .module) }
    static var hashtag: Image { Image("hashtag", bundle: .module) }
    static var hashtagCircle: Image { Image("hashtagCircle", bundle: .module) }
    static var hashtagRec: Image { Image("hashtagRec", bundle: .module) }
    static var headphones: Image { Image("headphones", bundle: .module) }
    static var headphones2: Image { Image("headphones2", bundle: .module) }
    static var heart: Image { Image("heart", bundle: .module) }
    static var heartSlash: Image { Image("heartSlash", bundle: .module) }
    static var history: Image { Image("history", bundle: .module) }
    static var historyRec: Image { Image("historyRec", bundle: .module) }
    static var home: Image { Image("home", bundle: .module) }
    static var home2: Image { Image("home2", bundle: .module) }
    static var home3: Image { Image("home3", bundle: .module) }
    static var home4: Image { Image("home4", bundle: .module) }
    static var Icon: Image { Image("Icon", bundle: .module) }
    static var image: Image { Image("image", bundle: .module) }
    static var image2: Image { Image("image2", bundle: .module) }
    static var image3: Image { Image("image3", bundle: .module) }
    static var imageCheck: Image { Image("imageCheck", bundle: .module) }
    static var imageCross: Image { Image("imageCross", bundle: .module) }
    static var imageDownload: Image { Image("imageDownload", bundle: .module) }
    static var imageEdit: Image { Image("imageEdit", bundle: .module) }
    static var imagePlus: Image { Image("imagePlus", bundle: .module) }
    static var imageSlash: Image { Image("imageSlash", bundle: .module) }
    static var imageUpload: Image { Image("imageUpload", bundle: .module) }
    //static var import: Image { Image("import", bundle: .module) }
    static var import2: Image { Image("import2", bundle: .module) }
    static var import3: Image { Image("import3", bundle: .module) }
    static var import4Rec: Image { Image("import4Rec", bundle: .module) }
    static var inbox: Image { Image("inbox", bundle: .module) }
    static var inboxFilled: Image { Image("inboxFilled", bundle: .module) }
    static var inboxIn: Image { Image("inboxIn", bundle: .module) }
    static var inboxOut: Image { Image("inboxOut", bundle: .module) }
    static var indentDecrease: Image { Image("indentDecrease", bundle: .module) }
    static var indentDecreaseRec: Image { Image("indentDecreaseRec", bundle: .module) }
    static var indentFirstLine: Image { Image("indentFirstLine", bundle: .module) }
    static var indentFirstLineRec: Image { Image("indentFirstLineRec", bundle: .module) }
    static var indentIncrease: Image { Image("indentIncrease", bundle: .module) }
    static var indentIncreaseRec: Image { Image("indentIncreaseRec", bundle: .module) }
    static var infinity: Image { Image("infinity", bundle: .module) }
    static var infinityRec: Image { Image("infinityRec", bundle: .module) }
    static var info: Image { Image("info", bundle: .module) }
    static var invoice: Image { Image("invoice", bundle: .module) }
    static var keyboard: Image { Image("keyboard", bundle: .module) }
    static var keyboardHide: Image { Image("keyboardHide", bundle: .module) }
    static var keyboardShow: Image { Image("keyboardShow", bundle: .module) }
    static var label4k: Image { Image("label4k", bundle: .module) }
    static var labelExplicit: Image { Image("labelExplicit", bundle: .module) }
    static var labelExplicit1: Image { Image("labelExplicit1", bundle: .module) }
    static var labelHd: Image { Image("labelHd", bundle: .module) }
    static var labelHq: Image { Image("labelHq", bundle: .module) }
    static var laptop: Image { Image("laptop", bundle: .module) }
    static var layers: Image { Image("layers", bundle: .module) }
    static var letterSpacing: Image { Image("letterSpacing", bundle: .module) }
    static var letterSpacing2: Image { Image("letterSpacing2", bundle: .module) }
    static var letterSpacing2Rec: Image { Image("letterSpacing2Rec", bundle: .module) }
    static var letterSpacingRec: Image { Image("letterSpacingRec", bundle: .module) }
    static var lifebuoy: Image { Image("lifebuoy", bundle: .module) }
    static var lightning: Image { Image("lightning", bundle: .module) }
    static var lightningSlash: Image { Image("lightningSlash", bundle: .module) }
    static var lineHeight: Image { Image("lineHeight", bundle: .module) }
    static var lineHeight2: Image { Image("lineHeight2", bundle: .module) }
    static var lineHeight2Rec: Image { Image("lineHeight2Rec", bundle: .module) }
    static var lineHeightRec: Image { Image("lineHeightRec", bundle: .module) }
    static var link: Image { Image("link", bundle: .module) }
    static var link1: Image { Image("link1", bundle: .module) }
    static var link1Rec: Image { Image("link1Rec", bundle: .module) }
    static var link2: Image { Image("link2", bundle: .module) }
    static var link2Rec: Image { Image("link2Rec", bundle: .module) }
    static var listOrdered: Image { Image("listOrdered", bundle: .module) }
    static var listOrderedRec: Image { Image("listOrderedRec", bundle: .module) }
    static var listUnordered: Image { Image("listUnordered", bundle: .module) }
    static var listUnordered2: Image { Image("listUnordered2", bundle: .module) }
    static var listUnordered2Rec: Image { Image("listUnordered2Rec", bundle: .module) }
    static var listUnordered3: Image { Image("listUnordered3", bundle: .module) }
    static var listUnordered3Rec: Image { Image("listUnordered3Rec", bundle: .module) }
    static var listUnordered4: Image { Image("listUnordered4", bundle: .module) }
    static var listUnordered4Rec: Image { Image("listUnordered4Rec", bundle: .module) }
    static var listUnordered5: Image { Image("listUnordered5", bundle: .module) }
    static var listUnordered5Rec: Image { Image("listUnordered5Rec", bundle: .module) }
    static var listUnorderedRec: Image { Image("listUnorderedRec", bundle: .module) }
    static var loader: Image { Image("loader", bundle: .module) }
    static var loader2: Image { Image("loader2", bundle: .module) }
    static var loader2Rec: Image { Image("loader2Rec", bundle: .module) }
    static var loaderRec: Image { Image("loaderRec", bundle: .module) }
    static var loadingTrolley: Image { Image("loadingTrolley", bundle: .module) }
    static var lock2: Image { Image("lock2", bundle: .module) }
    static var lock2Opened: Image { Image("lock2Opened", bundle: .module) }
    static var logIn: Image { Image("logIn", bundle: .module) }
    static var logIn2: Image { Image("logIn2", bundle: .module) }
    static var logIn3Rec: Image { Image("logIn3Rec", bundle: .module) }
    static var logOut: Image { Image("logOut", bundle: .module) }
    static var logOut2: Image { Image("logOut2", bundle: .module) }
    static var logOut21: Image { Image("logOut21", bundle: .module) }
    static var logOut3Rec: Image { Image("logOut3Rec", bundle: .module) }
    static var mapView: Image { Image("mapView", bundle: .module) }
    static var maximize: Image { Image("maximize", bundle: .module) }
    static var maximize2: Image { Image("maximize2", bundle: .module) }
    static var maximize2Flipped: Image { Image("maximize2Flipped", bundle: .module) }
    static var maximize2FlippedRec: Image { Image("maximize2FlippedRec", bundle: .module) }
    static var maximize2Rec: Image { Image("maximize2Rec", bundle: .module) }
    static var maximize3: Image { Image("maximize3", bundle: .module) }
    static var maximize3Rec: Image { Image("maximize3Rec", bundle: .module) }
    static var maximizeFlipped: Image { Image("maximizeFlipped", bundle: .module) }
    static var maximizeFlippedRec: Image { Image("maximizeFlippedRec", bundle: .module) }
    static var maximizeRec: Image { Image("maximizeRec", bundle: .module) }
    static var megaphone: Image { Image("megaphone", bundle: .module) }
    static var megaphoneFill: Image { Image("megaphoneFill", bundle: .module) }
    static var memoryCard: Image { Image("memoryCard", bundle: .module) }
    static var menu: Image { Image("menu", bundle: .module) }
    static var menu2: Image { Image("menu2", bundle: .module) }
    static var menu2Rec: Image { Image("menu2Rec", bundle: .module) }
    static var menuRec: Image { Image("menuRec", bundle: .module) }
    static var mic: Image { Image("mic", bundle: .module) }
    static var micFill: Image { Image("micFill", bundle: .module) }
    static var micSlash: Image { Image("micSlash", bundle: .module) }
    static var minimize: Image { Image("minimize", bundle: .module) }
    static var minimizeRec: Image { Image("minimizeRec", bundle: .module) }
    static var miniplayer: Image { Image("miniplayer", bundle: .module) }
    static var minus: Image { Image("minus", bundle: .module) }
    static var minusCircle: Image { Image("minusCircle", bundle: .module) }
    static var minusOctagon: Image { Image("minusOctagon", bundle: .module) }
    static var minusRec: Image { Image("minusRec", bundle: .module) }
    static var modules: Image { Image("modules", bundle: .module) }
    static var monitor: Image { Image("monitor", bundle: .module) }
    static var moon: Image { Image("moon", bundle: .module) }
    static var moreHoriz: Image { Image("moreHoriz", bundle: .module) }
    static var moreHorizRec: Image { Image("moreHorizRec", bundle: .module) }
    static var moreVert: Image { Image("moreVert", bundle: .module) }
    static var moreVertRec: Image { Image("moreVertRec", bundle: .module) }
    static var mouse: Image { Image("mouse", bundle: .module) }
    static var musicLibrary: Image { Image("musicLibrary", bundle: .module) }
    static var musicNote: Image { Image("musicNote", bundle: .module) }
    static var musicNote2: Image { Image("musicNote2", bundle: .module) }
    static var musicNote3: Image { Image("musicNote3", bundle: .module) }
    static var musicPlus: Image { Image("musicPlus", bundle: .module) }
    static var musicQueue: Image { Image("musicQueue", bundle: .module) }
    static var newRelease: Image { Image("newRelease", bundle: .module) }
    static var newspaper: Image { Image("newspaper", bundle: .module) }
    static var noteText: Image { Image("noteText", bundle: .module) }
    static var notificationIndicator: Image { Image("notificationIndicator", bundle: .module) }
    static var nut: Image { Image("nut", bundle: .module) }
    static var pageBreak: Image { Image("pageBreak", bundle: .module) }
    static var paintBucket: Image { Image("paintBucket", bundle: .module) }
    static var paintTool: Image { Image("paintTool", bundle: .module) }
    static var paperclip: Image { Image("paperclip", bundle: .module) }
    static var paperclip2: Image { Image("paperclip2", bundle: .module) }
    static var paperclip2Rec: Image { Image("paperclip2Rec", bundle: .module) }
    static var paperclip2Slash: Image { Image("paperclip2Slash", bundle: .module) }
    static var paperclip2SlashRec: Image { Image("paperclip2SlashRec", bundle: .module) }
    static var paperclipRec: Image { Image("paperclipRec", bundle: .module) }
    static var paperclipSlash: Image { Image("paperclipSlash", bundle: .module) }
    static var paperclipSlashRec: Image { Image("paperclipSlashRec", bundle: .module) }
    static var pause: Image { Image("pause", bundle: .module) }
    static var pauseCircle: Image { Image("pauseCircle", bundle: .module) }
    static var penTool: Image { Image("penTool", bundle: .module) }
    static var penTool2: Image { Image("penTool2", bundle: .module) }
    static var personIcon: Image{ Image("personIcon", bundle: .module) }
    static var pharagraphSpacing: Image { Image("pharagraphSpacing", bundle: .module) }
    static var pharagraphSpacingRec: Image { Image("pharagraphSpacingRec", bundle: .module) }
    static var phone: Image { Image("phone", bundle: .module) }
    static var pin: Image { Image("pin", bundle: .module) }
    static var pin2: Image { Image("pin2", bundle: .module) }
    static var pin3: Image { Image("pin3", bundle: .module) }
    static var pinCheck: Image { Image("pinCheck", bundle: .module) }
    static var pinCross: Image { Image("pinCross", bundle: .module) }
    static var pinMinus: Image { Image("pinMinus", bundle: .module) }
    static var pinPlus: Image { Image("pinPlus", bundle: .module) }
    static var pinSlash: Image { Image("pinSlash", bundle: .module) }
    static var planet: Image { Image("planet", bundle: .module) }
    static var play: Image { Image("play", bundle: .module) }
    static var playCircle: Image { Image("playCircle", bundle: .module) }
    static var playlist: Image { Image("playlist", bundle: .module) }
    static var playlistPlay: Image { Image("playlistPlay", bundle: .module) }
    static var playlistPlus: Image { Image("playlistPlus", bundle: .module) }
    static var playNext: Image { Image("playNext", bundle: .module) }
    static var playPrevious: Image { Image("playPrevious", bundle: .module) }
    static var playSlowmotion: Image { Image("playSlowmotion", bundle: .module) }
    static var plug: Image { Image("plug", bundle: .module) }
    static var plugSlash: Image { Image("plugSlash", bundle: .module) }
    static var plus: Image { Image("plus", bundle: .module) }
    static var plusCircle: Image { Image("plusCircle", bundle: .module) }
    static var plusRec: Image { Image("plusRec", bundle: .module) }
    static var power: Image { Image("power", bundle: .module) }
    static var powerRec: Image { Image("powerRec", bundle: .module) }
    static var presentationChart: Image { Image("presentationChart", bundle: .module) }
    static var presentationLine: Image { Image("presentationLine", bundle: .module) }
    static var printer: Image { Image("printer", bundle: .module) }
    static var printerSlash: Image { Image("printerSlash", bundle: .module) }
    static var processor: Image { Image("processor", bundle: .module) }
    static var question: Image { Image("question", bundle: .module) }
    static var quotes: Image { Image("quotes", bundle: .module) }
    static var quotes2: Image { Image("quotes2", bundle: .module) }
    static var radio: Image { Image("radio", bundle: .module) }
    static var receipt: Image { Image("receipt", bundle: .module) }
    static var record: Image { Image("record", bundle: .module) }
    static var redo: Image { Image("redo", bundle: .module) }
    static var redo2: Image { Image("redo2", bundle: .module) }
    static var redo2Rec: Image { Image("redo2Rec", bundle: .module) }
    static var redoRec: Image { Image("redoRec", bundle: .module) }
    static var refreshCcw: Image { Image("refreshCcw", bundle: .module) }
    static var refreshCcwAlert: Image { Image("refreshCcwAlert", bundle: .module) }
    static var refreshCcwAlertRec: Image { Image("refreshCcwAlertRec", bundle: .module) }
    static var refreshCcwRec: Image { Image("refreshCcwRec", bundle: .module) }
    static var refreshCw: Image { Image("refreshCw", bundle: .module) }
    static var refreshCwAlert: Image { Image("refreshCwAlert", bundle: .module) }
    static var refreshCwAlertRec: Image { Image("refreshCwAlertRec", bundle: .module) }
    static var refreshCwRec: Image { Image("refreshCwRec", bundle: .module) }
    //static var repeat: Image { Image("repeat", bundle: .module) }
    static var repeatOn: Image { Image("repeatOn", bundle: .module) }
    static var replay: Image { Image("replay", bundle: .module) }
    static var replay10: Image { Image("replay10", bundle: .module) }
    static var replay10Rec: Image { Image("replay10Rec", bundle: .module) }
    static var replay15: Image { Image("replay15", bundle: .module) }
    static var replay15Rec: Image { Image("replay15Rec", bundle: .module) }
    static var replay5: Image { Image("replay5", bundle: .module) }
    static var replay5Rec: Image { Image("replay5Rec", bundle: .module) }
    static var replayRec: Image { Image("replayRec", bundle: .module) }
    static var reply: Image { Image("reply", bundle: .module) }
    static var replyAll: Image { Image("replyAll", bundle: .module) }
    static var replyAllRec: Image { Image("replyAllRec", bundle: .module) }
    static var replyRec: Image { Image("replyRec", bundle: .module) }
    static var rocket: Image { Image("rocket", bundle: .module) }
    static var rocket2: Image { Image("rocket2", bundle: .module) }
    static var rotateCcw: Image { Image("rotateCcw", bundle: .module) }
    static var rotateCcwRec: Image { Image("rotateCcwRec", bundle: .module) }
    static var rotateCw: Image { Image("rotateCw", bundle: .module) }
    static var rotateCwRec: Image { Image("rotateCwRec", bundle: .module) }
    static var route: Image { Image("route", bundle: .module) }
    static var ruler: Image { Image("ruler", bundle: .module) }
    static var scale: Image { Image("scale", bundle: .module) }
    static var script: Image { Image("script", bundle: .module) }
    static var scriptRec: Image { Image("scriptRec", bundle: .module) }
    static var search: Image { Image("search", bundle: .module) }
    static var send: Image { Image("send", bundle: .module) }
    static var send2: Image { Image("send2", bundle: .module) }
    static var server2: Image { Image("server2", bundle: .module) }
    static var share: Image { Image("share", bundle: .module) }
    static var shoppingBag: Image { Image("shoppingBag", bundle: .module) }
    static var shoppingBag2: Image { Image("shoppingBag2", bundle: .module) }
    static var shoppingBasket: Image { Image("shoppingBasket", bundle: .module) }
    static var shoppingCart: Image { Image("shoppingCart", bundle: .module) }
    static var shoppingCart2: Image { Image("shoppingCart2", bundle: .module) }
    static var shuffle: Image { Image("shuffle", bundle: .module) }
    static var slash: Image { Image("slash", bundle: .module) }
    static var slidersHoriz: Image { Image("slidersHoriz", bundle: .module) }
    static var slidersHoriz2: Image { Image("slidersHoriz2", bundle: .module) }
    static var slidersVert: Image { Image("slidersVert", bundle: .module) }
    static var slidersVert2: Image { Image("slidersVert2", bundle: .module) }
    static var slowMoCheck: Image { Image("slowMoCheck", bundle: .module) }
    static var smallCaps: Image { Image("smallCaps", bundle: .module) }
    static var smallCaps2: Image { Image("smallCaps2", bundle: .module) }
    static var smallCaps2Rec: Image { Image("smallCaps2Rec", bundle: .module) }
    static var smallCapsRec: Image { Image("smallCapsRec", bundle: .module) }
    static var smartphone: Image { Image("smartphone", bundle: .module) }
    static var sortNumber: Image { Image("sortNumber", bundle: .module) }
    static var sortNumberRec: Image { Image("sortNumberRec", bundle: .module) }
    static var sortNumberReverse: Image { Image("sortNumberReverse", bundle: .module) }
    static var sortNumberReverseRec: Image { Image("sortNumberReverseRec", bundle: .module) }
    static var sortText: Image { Image("sortText", bundle: .module) }
    static var sortTextRec: Image { Image("sortTextRec", bundle: .module) }
    static var sortTextReverse: Image { Image("sortTextReverse", bundle: .module) }
    static var sortTextReverseRec: Image { Image("sortTextReverseRec", bundle: .module) }
    static var soundwave: Image { Image("soundwave", bundle: .module) }
    static var soundwaveRec: Image { Image("soundwaveRec", bundle: .module) }
    static var speaker: Image { Image("speaker", bundle: .module) }
    static var specialCharachers: Image { Image("specialCharachers", bundle: .module) }
    static var specialCharachersRec: Image { Image("specialCharachersRec", bundle: .module) }
    static var speed: Image { Image("speed", bundle: .module) }
    static var speedRec: Image { Image("speedRec", bundle: .module) }
    static var star: Image { Image("star", bundle: .module) }
    static var starSlash: Image { Image("starSlash", bundle: .module) }
    static var sticker: Image { Image("sticker", bundle: .module) }
    static var stop: Image { Image("stop", bundle: .module) }
    static var stopCircle: Image { Image("stopCircle", bundle: .module) }
    static var stopCircleFill: Image { Image("stopCircleFill", bundle: .module) }
    static var stopwatch: Image { Image("stopwatch", bundle: .module) }
    static var stopwatchSlash: Image { Image("stopwatchSlash", bundle: .module) }
    static var sun: Image { Image("sun", bundle: .module) }
    static var swatchbook: Image { Image("swatchbook", bundle: .module) }
    static var tablet: Image { Image("tablet", bundle: .module) }
    static var tag: Image { Image("tag", bundle: .module) }
    static var tag2: Image { Image("tag2", bundle: .module) }
    static var tags: Image { Image("tags", bundle: .module) }
    static var tags2: Image { Image("tags2", bundle: .module) }
    static var target: Image { Image("target", bundle: .module) }
    static var terminal: Image { Image("terminal", bundle: .module) }
    static var text: Image { Image("text", bundle: .module) }
    static var text2: Image { Image("text2", bundle: .module) }
    static var text2Rec: Image { Image("text2Rec", bundle: .module) }
    static var textBlock: Image { Image("textBlock", bundle: .module) }
    static var textBold: Image { Image("textBold", bundle: .module) }
    static var textBoldRec: Image { Image("textBoldRec", bundle: .module) }
    static var textFormat: Image { Image("textFormat", bundle: .module) }
    static var textItalic: Image { Image("textItalic", bundle: .module) }
    static var textItalicRec: Image { Image("textItalicRec", bundle: .module) }
    static var textRec: Image { Image("textRec", bundle: .module) }
    static var textSlash: Image { Image("textSlash", bundle: .module) }
    static var textSlash2: Image { Image("textSlash2", bundle: .module) }
    static var textSlash2Rec: Image { Image("textSlash2Rec", bundle: .module) }
    static var textSlashRec: Image { Image("textSlashRec", bundle: .module) }
    static var textStrikethrough: Image { Image("textStrikethrough", bundle: .module) }
    static var textStrikethroughRec: Image { Image("textStrikethroughRec", bundle: .module) }
    static var textUnderline: Image { Image("textUnderline", bundle: .module) }
    static var textUnderlineRec: Image { Image("textUnderlineRec", bundle: .module) }
    static var thermometer: Image { Image("thermometer", bundle: .module) }
    static var thumbsDown: Image { Image("thumbsDown", bundle: .module) }
    static var thumbsUp: Image { Image("thumbsUp", bundle: .module) }
    static var ticket: Image { Image("ticket", bundle: .module) }
    static var time: Image { Image("time", bundle: .module) }
    static var timer: Image { Image("timer", bundle: .module) }
    static var timer2: Image { Image("timer2", bundle: .module) }
    static var timer2Rec: Image { Image("timer2Rec", bundle: .module) }
    static var toggleOff: Image { Image("toggleOff", bundle: .module) }
    static var toggleOn: Image { Image("toggleOn", bundle: .module) }
    static var trash: Image { Image("trash", bundle: .module) }
    static var trash2: Image { Image("trash2", bundle: .module) }
    static var trendDown: Image { Image("trendDown", bundle: .module) }
    static var trendDownRec: Image { Image("trendDownRec", bundle: .module) }
    static var trendUp: Image { Image("trendUp", bundle: .module) }
    static var trendUpRec: Image { Image("trendUpRec", bundle: .module) }
    static var triggers: Image { Image("triggers", bundle: .module) }
    static var trophy: Image { Image("trophy", bundle: .module) }
    static var truck: Image { Image("truck", bundle: .module) }
    static var tv: Image { Image("tv", bundle: .module) }
    static var umbrella: Image { Image("umbrella", bundle: .module) }
    static var undo: Image { Image("undo", bundle: .module) }
    static var undo2: Image { Image("undo2", bundle: .module) }
    static var undo2Rec: Image { Image("undo2Rec", bundle: .module) }
    static var undoRec: Image { Image("undoRec", bundle: .module) }
    static var user: Image { Image("user", bundle: .module) }
    static var userAlert: Image { Image("userAlert", bundle: .module) }
    static var userArrowBl: Image { Image("userArrowBl", bundle: .module) }
    static var userArrowBottom: Image { Image("userArrowBottom", bundle: .module) }
    static var userArrowRight: Image { Image("userArrowRight", bundle: .module) }
    static var userArrowTop: Image { Image("userArrowTop", bundle: .module) }
    static var userArrowTr: Image { Image("userArrowTr", bundle: .module) }
    static var userCheck: Image { Image("userCheck", bundle: .module) }
    static var userCircle: Image { Image("userCircle", bundle: .module) }
    static var userCross: Image { Image("userCross", bundle: .module) }
    static var userMinus: Image { Image("userMinus", bundle: .module) }
    static var userPlus: Image { Image("userPlus", bundle: .module) }
    static var users: Image { Image("users", bundle: .module) }
    static var userSquare: Image { Image("userSquare", bundle: .module) }
    static var vector: Image { Image("vector", bundle: .module) }
    static var verified: Image { Image("verified", bundle: .module) }
    static var videoCamera: Image { Image("videoCamera", bundle: .module) }
    static var videoCameraSlash: Image { Image("videoCameraSlash", bundle: .module) }
    static var videoLibrary: Image { Image("videoLibrary", bundle: .module) }
    static var videoPlus: Image { Image("videoPlus", bundle: .module) }
    static var videoQueue: Image { Image("videoQueue", bundle: .module) }
    static var volumeCross: Image { Image("volumeCross", bundle: .module) }
    static var volumeHigh: Image { Image("volumeHigh", bundle: .module) }
    static var volumeLow: Image { Image("volumeLow", bundle: .module) }
    static var volumeMute: Image { Image("volumeMute", bundle: .module) }
    static var volumeSlash: Image { Image("volumeSlash", bundle: .module) }
    static var wallet: Image { Image("wallet", bundle: .module) }
    static var watch: Image { Image("watch", bundle: .module) }
    static var watch2: Image { Image("watch2", bundle: .module) }
    static var webcam: Image { Image("webcam", bundle: .module) }
    static var webcamSlash: Image { Image("webcamSlash", bundle: .module) }
    static var weight: Image { Image("weight", bundle: .module) }
    static var weighter: Image { Image("weighter", bundle: .module) }
    static var weighter2: Image { Image("weighter2", bundle: .module) }
    static var wheelchair: Image { Image("wheelchair", bundle: .module) }
    static var wheelchairRec: Image { Image("wheelchairRec", bundle: .module) }
    static var wifi: Image { Image("wifi", bundle: .module) }
    static var wifiRec: Image { Image("wifiRec", bundle: .module) }
    static var wifiSlash: Image { Image("wifiSlash", bundle: .module) }
    static var wifiSlashRec: Image { Image("wifiSlashRec", bundle: .module) }
    static var wrapText: Image { Image("wrapText", bundle: .module) }
    static var wrapTextRec: Image { Image("wrapTextRec", bundle: .module) }
    static var wrench: Image { Image("wrench", bundle: .module) }
    static var yinYang: Image { Image("yinYang", bundle: .module) }
    static var zoomIn: Image { Image("zoomIn", bundle: .module) }
    static var zoomOut: Image { Image("zoomOut", bundle: .module) }
}
